//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaBattle.GameServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRequest", Namespace="http://schemas.datacontract.org/2004/07/Common.Request", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SeaBattle.GameServiceReference.CreateGameRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SeaBattle.GameServiceReference.ConnectToGameRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SeaBattle.GameServiceReference.SendReadyRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SeaBattle.GameServiceReference.SendMessageRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SeaBattle.GameServiceReference.AuthorizeRequest))]
    public partial class BaseRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateGameRequest", Namespace="http://schemas.datacontract.org/2004/07/Common.Request", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class CreateGameRequest : SeaBattle.GameServiceReference.BaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectToGameRequest", Namespace="http://schemas.datacontract.org/2004/07/Common.Request", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ConnectToGameRequest : SeaBattle.GameServiceReference.BaseRequest {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendReadyRequest", Namespace="http://schemas.datacontract.org/2004/07/Common.Request", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class SendReadyRequest : SeaBattle.GameServiceReference.BaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SeaBattle.GameServiceReference.BattleMap ClientBattleMapField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SeaBattle.GameServiceReference.BattleMap ClientBattleMap {
            get {
                return this.ClientBattleMapField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientBattleMapField, value) != true)) {
                    this.ClientBattleMapField = value;
                    this.RaisePropertyChanged("ClientBattleMap");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendMessageRequest", Namespace="http://schemas.datacontract.org/2004/07/Common.Request", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class SendMessageRequest : SeaBattle.GameServiceReference.BaseRequest {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthorizeRequest", Namespace="http://schemas.datacontract.org/2004/07/Common.Request", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class AuthorizeRequest : SeaBattle.GameServiceReference.BaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BattleMap", Namespace="http://schemas.datacontract.org/2004/07/Entity.GameEntities")]
    [System.SerializableAttribute()]
    public partial class BattleMap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SeaBattle.GameServiceReference.Ship[][] ShipMapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SeaBattle.GameServiceReference.Ship[][] ShipZoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SeaBattle.GameServiceReference.Ship[] ShipsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SeaBattle.GameServiceReference.Ship[][] ShipMap {
            get {
                return this.ShipMapField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipMapField, value) != true)) {
                    this.ShipMapField = value;
                    this.RaisePropertyChanged("ShipMap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SeaBattle.GameServiceReference.Ship[][] ShipZone {
            get {
                return this.ShipZoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipZoneField, value) != true)) {
                    this.ShipZoneField = value;
                    this.RaisePropertyChanged("ShipZone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SeaBattle.GameServiceReference.Ship[] Ships {
            get {
                return this.ShipsField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipsField, value) != true)) {
                    this.ShipsField = value;
                    this.RaisePropertyChanged("Ships");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ship", Namespace="http://schemas.datacontract.org/2004/07/Entity.GameEntities")]
    [System.SerializableAttribute()]
    public partial class Ship : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SeaBattle.GameServiceReference.Deck[] DecksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsKilledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SeaBattle.GameServiceReference.ShipOrientation OrientationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SeaBattle.GameServiceReference.XYCoordinate StartPointField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SeaBattle.GameServiceReference.Deck[] Decks {
            get {
                return this.DecksField;
            }
            set {
                if ((object.ReferenceEquals(this.DecksField, value) != true)) {
                    this.DecksField = value;
                    this.RaisePropertyChanged("Decks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsKilled {
            get {
                return this.IsKilledField;
            }
            set {
                if ((this.IsKilledField.Equals(value) != true)) {
                    this.IsKilledField = value;
                    this.RaisePropertyChanged("IsKilled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SeaBattle.GameServiceReference.ShipOrientation Orientation {
            get {
                return this.OrientationField;
            }
            set {
                if ((this.OrientationField.Equals(value) != true)) {
                    this.OrientationField = value;
                    this.RaisePropertyChanged("Orientation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SeaBattle.GameServiceReference.XYCoordinate StartPoint {
            get {
                return this.StartPointField;
            }
            set {
                if ((object.ReferenceEquals(this.StartPointField, value) != true)) {
                    this.StartPointField = value;
                    this.RaisePropertyChanged("StartPoint");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XYCoordinate", Namespace="http://schemas.datacontract.org/2004/07/Entity.GameEntities")]
    [System.SerializableAttribute()]
    public partial class XYCoordinate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int X {
            get {
                return this.XField;
            }
            set {
                if ((this.XField.Equals(value) != true)) {
                    this.XField = value;
                    this.RaisePropertyChanged("X");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Y {
            get {
                return this.YField;
            }
            set {
                if ((this.YField.Equals(value) != true)) {
                    this.YField = value;
                    this.RaisePropertyChanged("Y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Deck", Namespace="http://schemas.datacontract.org/2004/07/Entity.GameEntities")]
    [System.SerializableAttribute()]
    public partial class Deck : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SeaBattle.GameServiceReference.DeckStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SeaBattle.GameServiceReference.DeckStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShipOrientation", Namespace="http://schemas.datacontract.org/2004/07/Entity.Enums")]
    public enum ShipOrientation : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Horisontal = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Vertical = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeckStatus", Namespace="http://schemas.datacontract.org/2004/07/Entity.Enums")]
    public enum DeckStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ok = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Damaged = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://schemas.datacontract.org/2004/07/Common.Respose")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SeaBattle.GameServiceReference.RegisterResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SeaBattle.GameServiceReference.CreateGameResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SeaBattle.GameServiceReference.ShotResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SeaBattle.GameServiceReference.CurentGameResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SeaBattle.GameServiceReference.SendReadyResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SeaBattle.GameServiceReference.GetTopPlayersResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SeaBattle.GameServiceReference.GetLastGamesResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SeaBattle.GameServiceReference.GetListGamesResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SeaBattle.GameServiceReference.EndGameResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SeaBattle.GameServiceReference.AbortGameResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SeaBattle.GameServiceReference.StartChatResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SeaBattle.GameServiceReference.RecieveMessageResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SeaBattle.GameServiceReference.AuthorizeResponse))]
    public partial class BaseResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterResponse", Namespace="http://schemas.datacontract.org/2004/07/Common.Respose")]
    [System.SerializableAttribute()]
    public partial class RegisterResponse : SeaBattle.GameServiceReference.BaseResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateGameResponse", Namespace="http://schemas.datacontract.org/2004/07/Common.Respose")]
    [System.SerializableAttribute()]
    public partial class CreateGameResponse : SeaBattle.GameServiceReference.BaseResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShotResponse", Namespace="http://schemas.datacontract.org/2004/07/Common.Respose")]
    [System.SerializableAttribute()]
    public partial class ShotResponse : SeaBattle.GameServiceReference.BaseResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CurentGameResponse", Namespace="http://schemas.datacontract.org/2004/07/Common.Respose")]
    [System.SerializableAttribute()]
    public partial class CurentGameResponse : SeaBattle.GameServiceReference.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SeaBattle.GameServiceReference.Game CurrentGameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SeaBattle.GameServiceReference.Game CurrentGame {
            get {
                return this.CurrentGameField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentGameField, value) != true)) {
                    this.CurrentGameField = value;
                    this.RaisePropertyChanged("CurrentGame");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendReadyResponse", Namespace="http://schemas.datacontract.org/2004/07/Common.Respose")]
    [System.SerializableAttribute()]
    public partial class SendReadyResponse : SeaBattle.GameServiceReference.BaseResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTopPlayersResponse", Namespace="http://schemas.datacontract.org/2004/07/Common.Respose")]
    [System.SerializableAttribute()]
    public partial class GetTopPlayersResponse : SeaBattle.GameServiceReference.BaseResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLastGamesResponse", Namespace="http://schemas.datacontract.org/2004/07/Common.Respose")]
    [System.SerializableAttribute()]
    public partial class GetLastGamesResponse : SeaBattle.GameServiceReference.BaseResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetListGamesResponse", Namespace="http://schemas.datacontract.org/2004/07/Common.Respose")]
    [System.SerializableAttribute()]
    public partial class GetListGamesResponse : SeaBattle.GameServiceReference.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SeaBattle.GameServiceReference.Game[] GamesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SeaBattle.GameServiceReference.Game[] Games {
            get {
                return this.GamesField;
            }
            set {
                if ((object.ReferenceEquals(this.GamesField, value) != true)) {
                    this.GamesField = value;
                    this.RaisePropertyChanged("Games");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EndGameResponse", Namespace="http://schemas.datacontract.org/2004/07/Common.Respose")]
    [System.SerializableAttribute()]
    public partial class EndGameResponse : SeaBattle.GameServiceReference.BaseResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbortGameResponse", Namespace="http://schemas.datacontract.org/2004/07/Common.Respose")]
    [System.SerializableAttribute()]
    public partial class AbortGameResponse : SeaBattle.GameServiceReference.BaseResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StartChatResponse", Namespace="http://schemas.datacontract.org/2004/07/Common.Respose")]
    [System.SerializableAttribute()]
    public partial class StartChatResponse : SeaBattle.GameServiceReference.BaseResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecieveMessageResponse", Namespace="http://schemas.datacontract.org/2004/07/Common.Respose")]
    [System.SerializableAttribute()]
    public partial class RecieveMessageResponse : SeaBattle.GameServiceReference.BaseResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthorizeResponse", Namespace="http://schemas.datacontract.org/2004/07/Common.Respose")]
    [System.SerializableAttribute()]
    public partial class AuthorizeResponse : SeaBattle.GameServiceReference.BaseResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Game", Namespace="http://schemas.datacontract.org/2004/07/Entity.DataBaseEntities")]
    [System.SerializableAttribute()]
    public partial class Game : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdPlayer1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdPlayer2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdWinnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDateTime {
            get {
                return this.CreateDateTimeField;
            }
            set {
                if ((this.CreateDateTimeField.Equals(value) != true)) {
                    this.CreateDateTimeField = value;
                    this.RaisePropertyChanged("CreateDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDateTime {
            get {
                return this.EndDateTimeField;
            }
            set {
                if ((this.EndDateTimeField.Equals(value) != true)) {
                    this.EndDateTimeField = value;
                    this.RaisePropertyChanged("EndDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdPlayer1 {
            get {
                return this.IdPlayer1Field;
            }
            set {
                if ((this.IdPlayer1Field.Equals(value) != true)) {
                    this.IdPlayer1Field = value;
                    this.RaisePropertyChanged("IdPlayer1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdPlayer2 {
            get {
                return this.IdPlayer2Field;
            }
            set {
                if ((this.IdPlayer2Field.Equals(value) != true)) {
                    this.IdPlayer2Field = value;
                    this.RaisePropertyChanged("IdPlayer2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdWinner {
            get {
                return this.IdWinnerField;
            }
            set {
                if ((this.IdWinnerField.Equals(value) != true)) {
                    this.IdWinnerField = value;
                    this.RaisePropertyChanged("IdWinner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDateTime {
            get {
                return this.StartDateTimeField;
            }
            set {
                if ((this.StartDateTimeField.Equals(value) != true)) {
                    this.StartDateTimeField = value;
                    this.RaisePropertyChanged("StartDateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterRequest", Namespace="http://schemas.datacontract.org/2004/07/Common.Request")]
    [System.SerializableAttribute()]
    public partial class RegisterRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Shot", Namespace="http://schemas.datacontract.org/2004/07/Entity.GameEntities")]
    [System.SerializableAttribute()]
    public partial class Shot : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SeaBattle.GameServiceReference.ShotStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SeaBattle.GameServiceReference.XYCoordinate XyCoordinateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SeaBattle.GameServiceReference.ShotStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SeaBattle.GameServiceReference.XYCoordinate XyCoordinate {
            get {
                return this.XyCoordinateField;
            }
            set {
                if ((object.ReferenceEquals(this.XyCoordinateField, value) != true)) {
                    this.XyCoordinateField = value;
                    this.RaisePropertyChanged("XyCoordinate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShotStatus", Namespace="http://schemas.datacontract.org/2004/07/Entity.Enums")]
    public enum ShotStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Missed = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hit = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameServiceReference.IService", CallbackContract=typeof(SeaBattle.GameServiceReference.IServiceCallback))]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Authorize", ReplyAction="http://tempuri.org/IService/AuthorizeResponse")]
        SeaBattle.GameServiceReference.AuthorizeResponse Authorize(SeaBattle.GameServiceReference.AuthorizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Authorize", ReplyAction="http://tempuri.org/IService/AuthorizeResponse")]
        System.Threading.Tasks.Task<SeaBattle.GameServiceReference.AuthorizeResponse> AuthorizeAsync(SeaBattle.GameServiceReference.AuthorizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Register", ReplyAction="http://tempuri.org/IService/RegisterResponse")]
        SeaBattle.GameServiceReference.RegisterResponse Register(SeaBattle.GameServiceReference.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Register", ReplyAction="http://tempuri.org/IService/RegisterResponse")]
        System.Threading.Tasks.Task<SeaBattle.GameServiceReference.RegisterResponse> RegisterAsync(SeaBattle.GameServiceReference.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateGame", ReplyAction="http://tempuri.org/IService/CreateGameResponse")]
        SeaBattle.GameServiceReference.CreateGameResponse CreateGame(SeaBattle.GameServiceReference.CreateGameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CreateGame", ReplyAction="http://tempuri.org/IService/CreateGameResponse")]
        System.Threading.Tasks.Task<SeaBattle.GameServiceReference.CreateGameResponse> CreateGameAsync(SeaBattle.GameServiceReference.CreateGameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DoShot", ReplyAction="http://tempuri.org/IService/DoShotResponse")]
        SeaBattle.GameServiceReference.ShotResponse DoShot(SeaBattle.GameServiceReference.Shot shot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DoShot", ReplyAction="http://tempuri.org/IService/DoShotResponse")]
        System.Threading.Tasks.Task<SeaBattle.GameServiceReference.ShotResponse> DoShotAsync(SeaBattle.GameServiceReference.Shot shot);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConnectToGame", ReplyAction="http://tempuri.org/IService/ConnectToGameResponse")]
        SeaBattle.GameServiceReference.CurentGameResponse ConnectToGame(SeaBattle.GameServiceReference.ConnectToGameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConnectToGame", ReplyAction="http://tempuri.org/IService/ConnectToGameResponse")]
        System.Threading.Tasks.Task<SeaBattle.GameServiceReference.CurentGameResponse> ConnectToGameAsync(SeaBattle.GameServiceReference.ConnectToGameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SendReady", ReplyAction="http://tempuri.org/IService/SendReadyResponse")]
        SeaBattle.GameServiceReference.SendReadyResponse SendReady(SeaBattle.GameServiceReference.SendReadyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SendReady", ReplyAction="http://tempuri.org/IService/SendReadyResponse")]
        System.Threading.Tasks.Task<SeaBattle.GameServiceReference.SendReadyResponse> SendReadyAsync(SeaBattle.GameServiceReference.SendReadyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTopPlayers", ReplyAction="http://tempuri.org/IService/GetTopPlayersResponse")]
        SeaBattle.GameServiceReference.GetTopPlayersResponse GetTopPlayers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTopPlayers", ReplyAction="http://tempuri.org/IService/GetTopPlayersResponse")]
        System.Threading.Tasks.Task<SeaBattle.GameServiceReference.GetTopPlayersResponse> GetTopPlayersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetLastGames", ReplyAction="http://tempuri.org/IService/GetLastGamesResponse")]
        SeaBattle.GameServiceReference.GetLastGamesResponse GetLastGames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetLastGames", ReplyAction="http://tempuri.org/IService/GetLastGamesResponse")]
        System.Threading.Tasks.Task<SeaBattle.GameServiceReference.GetLastGamesResponse> GetLastGamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/SendMessage")]
        void SendMessage(SeaBattle.GameServiceReference.SendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/SendMessage")]
        System.Threading.Tasks.Task SendMessageAsync(SeaBattle.GameServiceReference.SendMessageRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/DoShotCallback")]
        void DoShotCallback(SeaBattle.GameServiceReference.ShotResponse shot);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/GetListAvailableGames")]
        void GetListAvailableGames(SeaBattle.GameServiceReference.GetListGamesResponse response);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/GiveConnectedOpponentInfo")]
        void GiveConnectedOpponentInfo(SeaBattle.GameServiceReference.CurentGameResponse response);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/SendOpponentIsReady")]
        void SendOpponentIsReady();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/StartGame")]
        void StartGame();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/EndGame")]
        void EndGame(SeaBattle.GameServiceReference.EndGameResponse response);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/AbortGame")]
        void AbortGame(SeaBattle.GameServiceReference.AbortGameResponse response);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/StartChat")]
        void StartChat(SeaBattle.GameServiceReference.StartChatResponse response);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/RecieveMessage")]
        void RecieveMessage(SeaBattle.GameServiceReference.RecieveMessageResponse response);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : SeaBattle.GameServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.DuplexClientBase<SeaBattle.GameServiceReference.IService>, SeaBattle.GameServiceReference.IService {
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public SeaBattle.GameServiceReference.AuthorizeResponse Authorize(SeaBattle.GameServiceReference.AuthorizeRequest request) {
            return base.Channel.Authorize(request);
        }
        
        public System.Threading.Tasks.Task<SeaBattle.GameServiceReference.AuthorizeResponse> AuthorizeAsync(SeaBattle.GameServiceReference.AuthorizeRequest request) {
            return base.Channel.AuthorizeAsync(request);
        }
        
        public SeaBattle.GameServiceReference.RegisterResponse Register(SeaBattle.GameServiceReference.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public System.Threading.Tasks.Task<SeaBattle.GameServiceReference.RegisterResponse> RegisterAsync(SeaBattle.GameServiceReference.RegisterRequest request) {
            return base.Channel.RegisterAsync(request);
        }
        
        public SeaBattle.GameServiceReference.CreateGameResponse CreateGame(SeaBattle.GameServiceReference.CreateGameRequest request) {
            return base.Channel.CreateGame(request);
        }
        
        public System.Threading.Tasks.Task<SeaBattle.GameServiceReference.CreateGameResponse> CreateGameAsync(SeaBattle.GameServiceReference.CreateGameRequest request) {
            return base.Channel.CreateGameAsync(request);
        }
        
        public SeaBattle.GameServiceReference.ShotResponse DoShot(SeaBattle.GameServiceReference.Shot shot) {
            return base.Channel.DoShot(shot);
        }
        
        public System.Threading.Tasks.Task<SeaBattle.GameServiceReference.ShotResponse> DoShotAsync(SeaBattle.GameServiceReference.Shot shot) {
            return base.Channel.DoShotAsync(shot);
        }
        
        public SeaBattle.GameServiceReference.CurentGameResponse ConnectToGame(SeaBattle.GameServiceReference.ConnectToGameRequest request) {
            return base.Channel.ConnectToGame(request);
        }
        
        public System.Threading.Tasks.Task<SeaBattle.GameServiceReference.CurentGameResponse> ConnectToGameAsync(SeaBattle.GameServiceReference.ConnectToGameRequest request) {
            return base.Channel.ConnectToGameAsync(request);
        }
        
        public SeaBattle.GameServiceReference.SendReadyResponse SendReady(SeaBattle.GameServiceReference.SendReadyRequest request) {
            return base.Channel.SendReady(request);
        }
        
        public System.Threading.Tasks.Task<SeaBattle.GameServiceReference.SendReadyResponse> SendReadyAsync(SeaBattle.GameServiceReference.SendReadyRequest request) {
            return base.Channel.SendReadyAsync(request);
        }
        
        public SeaBattle.GameServiceReference.GetTopPlayersResponse GetTopPlayers() {
            return base.Channel.GetTopPlayers();
        }
        
        public System.Threading.Tasks.Task<SeaBattle.GameServiceReference.GetTopPlayersResponse> GetTopPlayersAsync() {
            return base.Channel.GetTopPlayersAsync();
        }
        
        public SeaBattle.GameServiceReference.GetLastGamesResponse GetLastGames() {
            return base.Channel.GetLastGames();
        }
        
        public System.Threading.Tasks.Task<SeaBattle.GameServiceReference.GetLastGamesResponse> GetLastGamesAsync() {
            return base.Channel.GetLastGamesAsync();
        }
        
        public void SendMessage(SeaBattle.GameServiceReference.SendMessageRequest request) {
            base.Channel.SendMessage(request);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(SeaBattle.GameServiceReference.SendMessageRequest request) {
            return base.Channel.SendMessageAsync(request);
        }
    }
}
